### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by alechjo1** [ZuinigeRijder/hyundai_kia_connect_monitor#36]
I get the following TypeError. I'm using Python3.8 (with no possibility to upgrade). So maybe there is a way to solve this for Python3.8 users?
    
[0] => Traceback (most recent call last):
    [1] =>   File "monitor/monitor.py", line 42, in 
    [2] =>     from hyundai_kia_connect_api import VehicleManager
    [3] =>   File "/www/htdocs/xxx/ioniq/monitor/hyundai_kia_connect_api/__init__.py", line 3, in 
    [4] =>     from .ApiImpl import ApiImpl, ClimateRequestOptions
    [5] =>   File "/www/htdocs/xxx/ioniq/monitor/hyundai_kia_connect_api/ApiImpl.py", line 11, in 
    [6] =>     from .Vehicle import Vehicle
    [7] =>   File "/www/htdocs/xxx/ioniq/monitor/hyundai_kia_connect_api/Vehicle.py", line 34, in 
    [8] =>     class MonthTripInfo:
    [9] =>   File "/www/htdocs/xxx/ioniq/monitor/hyundai_kia_connect_api/Vehicle.py", line 39, in MonthTripInfo
    [10] =>     day_list: list[DayTripCounts] = field(default_factory=list)
    [11] => TypeError: 'type' object is not subscriptable

**Comment by ZuinigeRijder** [comment]
hyundai_kia_connect_monitor depends on hyundai_kia_connect_api, which also depends on Python 3.9 onwards. Actually the source code you mention is part of the  hyundai_kia_connect_api. I am not owner of that code, although I did provide some improvements.

Why can you not upgrade to Python 3.9?

**Comment by alechjo1** [comment]
I am using a shared Webserver, and with the currently available systems their only offer 3.8.

**Comment by ZuinigeRijder** [comment]
Which operating System is running? Linux? Windows?

Multiple versions of python can be installed, using https://github.com/pyenv/pyenv or https://github.com/pyenv-win/pyenv-win

**Comment by alechjo1** [comment]
Its Linux Ubuntu 20, they already have several versions available, but 3.8 as the latest. Maybe in the future they will offer Ubuntu 22 with Python 3.10. 

I guess I will need to use some other Server (Raspberry), but I wanted to avoid that and use the tools that I have and know. 

Thanks anyway for your Work!
